name: Metrics-Overview
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          plugin_isocalendar: yes
          
          plugin_lines: yes
          
          plugin_languages: yes

          plugin_topics: yes
          plugin_topics_mode: labels