name: GitHub Metrics
on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:
  push:
    branches: ["master", "main"]

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: "images/metrics-overview.svg"
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          
          plugin_isocalendar: yes
          plugin_lines: yes
          plugin_languages: yes
          plugin_topics: yes
          plugin_topics_mode: labels

      - uses: lowlighter/metrics@latest
        with:
          filename: "images/metrics-code.svg"
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          
          plugin_code: yes
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_user: GongZhenCN
          plugin_wakatime_section: time

      - uses: lowlighter/metrics@latest
        with:
          filename: "images/metrics-anime.svg"
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          
          plugin_anilist: yes
          plugin_anilist_user: GongZhenCN
          plugin_anilist_medias: anime,manga
          plugin_anilist_sections: watching,characters
          plugin_anilist_limit: 1
          plugin_anilist_limit_characters: 5