name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          plugin_isocalendar: yes
          
          plugin_lines: yes
          
          plugin_languages: yes

          plugin_topics: yes
          plugin_topics_mode: labels

          plugin_anilist: yes
          plugin_anilist_user: GongZhenCN
          plugin_anilist_medias: anime,manga
          plugin_anilist_sections: watching,characters
          plugin_anilist_limit: 1
          plugin_anilist_limit_characters: 5

          plugin_music: no
          plugin_music_provider: apple
          plugin_music_mode: recent

          plugin_steam: no
          plugin_steam_token: B94CC9DFA3D9D3865F9778A24D2589D3
          plugin_steam_user: 76561199037641939
          plugin_steam_sections: player,recently-played
